### Get all staff
GET http://localhost:3504/staff

### Login
POST http://localhost:3504/staff/login
content-type: application/json

{
    "email" : "",
    "password" : ""
}

### Register
POST http://localhost:3504/staff/register
content-type: application/json

{
    "email" : "example@example.com",
    "password" : "123456789"
}

